repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      - id: terraform_trivy
        args:
          - --args=--severity=HIGH,CRITICAL
      - id: terraform_checkov
        args:
          - --args=--quiet
          - --args=--compact
          - --args=--skip-check CKV_AWS_158,CKV_AWS_116,CKV_AWS_117,CKV_AWS_237,CKV_AWS_120,CKV_AWS_225,CKV2_AWS_5,CKV2_AWS_29,CKV_AWS_144,CKV2_AWS_51,CKV2_AWS_57,CKV2_AWS_62
